"""Create widget table

Revision ID: 564fba50d3ed
Revises:
Create Date: 2025-06-04 16:32:21.713683

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "564fba50d3ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("number_of_parts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("number_of_parts > 0", name="positive_parts"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_widgets_created_at"), "widgets", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_widgets_name"), "widgets", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_widgets_name"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_created_at"), table_name="widgets")
    op.drop_table("widgets")
    # ### end Alembic commands ###
